### PR TITLE
blackboard-tx2.conf: Add ODMDATA

### PR DESCRIPTION
**Pull request by sjdrc**
Changelog-entry: Add ODMDATA field for correct USB 3.0 port mapping
Signed-off-by: Sebastien Collier <sebastien@black.ai>

### CODE REVIEW

**Comment by sjdrc** [comment]
Unfortunately, I missed this when adding support for the blackboard in my last pull request. Would it be possible to get this into staging before the weekend?

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Sure. It's deployed to staging now.

**Comment by acostach** [comment]
@sjdrc We are currently adding support for LT4 32.2 at: https://github.com/balena-os/balena-jetson/pull/13. If you wish to use it with Blackboard TX2, you can open a PR in that repository with any updates you find necessary. (dtb, configs, etc).

**Pull request merged**
