### PR TITLE
Include tegra misc utilities

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by compiaffe** [comment]
I just kicked off a build. Will report here later today (CET).

**Comment by compiaffe** [comment]
Builds fine, `nvpmodel -q` and `nvpmodel -m` work but a change is not persistent across reboots, even if one first mounts the filesystem as readwrite: `mount -o remount,rw /`

However, write mounting the filesystem as described and then changing the default in `/etc/nvpmodel.conf` works and persists.

How would you recommend to set the nvpmodel to i.e. 0 as the default for a build? I guess I could create a udev rule that triggers this, too. Any other ideas?

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
What change do you need in /etc/nvpmodel.conf?

**Comment by compiaffe** [comment]
We would like to have the nvpmodel default to 0 (full power mode), rather than 3. (see https://www.jetsonhacks.com/2017/03/25/nvpmodel-nvidia-jetson-tx2-development-kit/)

But I believe that is very application specific. So it might be great to have an option to set this when building the image.
Or setting this somehow on boot, that's where I was thinking of the custom udev rules that are supported via Balena. Any other ideas?

**Comment by compiaffe** [comment]
@floion I found a simple way / workaround to set this using udev rules:
https://forums.balena.io/t/nvpmodel-not-installed-on-jetson-tx2-yocto-image/4395/14?u=rapha

**Pull request merged**
