### PR TITLE
Update rust to 1.33

### PR DESCRIPTION
**Pull request by agherzan**

### CODE REVIEW

**Comment by agherzan** [comment]
@resin-jenkins add to whitelist

**Comment by agherzan** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Comment by floion** [comment]
@balena-ci retest

**Comment by agherzan** [comment]
@resin-jenkins retest

**Comment by floion** [comment]
I think `retest` is not know to jenkins. Only:

> When a new pull request is opened in the project and the author of the pull request isn't white-listed, builder will ask "Can one of the admins verify this patch?".

>"ok to test" to accept this pull request for testing
"test this please" for a one time test run
"add to whitelist" to add the author to the whitelist
If the build fails for other various reasons you can rebuild.

> "retest this please" to start a new build

from https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

**Pull request merged**
